### ISSUE TITLE
Request: ability to disable last modified timestamp

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#30]
![screenshot of last modified](https://github.com/1bl4z3r/hermit-V2/assets/8990777/cfb76dd5-4213-4793-9193-b243e15b706d)

I see this is part of `single.html` in v1.0.2, where it has an `if .Lastmod` conditional.

Any chance we can expose a new config parameter to turn off this behavior?  I like the default "creation only" timestamp. Alternately, maybe a post front matter parameter could be useful too

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

If you dont supply `Lastmod` in posts' front matter, it will not show `Modified` section.

Le me know if you were able to resolve.

**Comment by jamesbraza** [comment]
For me, my front matter is (it has no `Lastmod`):

```md
---
title: "Foo"
date: 2023-04-23
draft: false
tags: ["article"]
---
```

Even explicitly adding `Lastmod: false` did not disable the "Modified" text.  What am I missing?

**Comment by 1bl4z3r** [comment]
Hi again,

It seems to be very strange indeed.

In [this post](http://localhost:1313/hermit-V2/posts/typography/), I have supplied `Lastmod` as follows.

```yaml
title: "Typography"
slug : 'typography'
date: 2023-07-22T14:36:33+05:30
draft: false
featuredImg: ""
description : 'Integer lobortis vulputate mauris quis maximus. Vestibulum ac eros porttitor, auctor sem sed, tincidunt nulla. In sit amet tincidunt ex.'
tags: 
  - Demo
  - Typography
Lastmod : 2023-08-15T15:36:33+05:30
```

I get :

![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/53747b36-bd89-4174-8393-cfe6fe8eb498)

Now if I remove:

```yaml
title: "Typography"
slug : 'typography'
date: 2023-07-22T14:36:33+05:30
draft: false
featuredImg: ""
description : 'Integer lobortis vulputate mauris quis maximus. Vestibulum ac eros porttitor, auctor sem sed, tincidunt nulla. In sit amet tincidunt ex.'
tags: 
  - Demo
  - Typography
```
I don't get the Lastmod section.
![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/80c5057c-2da5-47c4-a245-8edcb803af80)

Pleas re-check your config if everything is properly formatted and/or do a full recheck on all the files if Lastmod is given somewhere.
