### ISSUE TITLE
Share layouts between different menus

### ISSUE THREAD

**Issue by v0y4g3r** [1bl4z3r/hermit-V2#86]
Hi 👋  I'm considering switching from a self-maintained hermit to hermit-v2. But I have a question:

Suppose I have two menus in hugo.toml:

```toml
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Gallery"
    url = "gallery/"
    weight = 15
```

Can I use the same layout as `/posts` for those pages in `/gallery`? If not, is there a way to achieve that effect? I'd be happy to work on it.
